version: '3'

services:
  c7-systemd-sshd:
    build: .
    ports:
      - "22:22"
      - "2375:2375"
      - "8000:80"
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - c7_sshd_network
networks:
  c7_sshd_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
